export const AI_REPOST_MODEL = 'gpt-5.6-luna'

export const AI_REPOST_BATCH_SIZE = 10
export const AI_REPOST_BATCH_DELAY_MS = 15_000
export const AI_REPOST_FALLBACK_MIN_POSTS = 3
export const AI_REPOST_BATCH_TIMEOUT_MS = 120_000
export const AI_REPOST_SEARCH_TIMEOUT_MS = 15_000
export const AI_REPOST_RECENT_WINDOW_MS = 5 * 60 * 60 * 1000

export const AI_REPOST_SOCIAL_DOMAINS = [
  'apnews.com',
  'abcnews.go.com',
  'adweek.com',
  'aljazeera.com',
  'axios.com',
  'barrons.com',
  'bbc.com',
  'bloomberg.com',
  'businessinsider.com',
  'bsky.app',
  'cbsnews.com',
  'cnbc.com',
  'cnet.com',
  'cnn.com',
  'economictimes.indiatimes.com',
  'economist.com',
  'engadget.com',
  'arstechnica.com',
  'facebook.com',
  'fastcompany.com',
  'finance.yahoo.com',
  'foxnews.com',
  'forbes.com',
  'fortune.com',
  'ft.com',
  'gizmodo.com',
  'inc.com',
  'instagram.com',
  'investopedia.com',
  'linkedin.com',
  'marketwatch.com',
  'mashable.com',
  'mastodon.social',
  'mediagazer.com',
  'medium.com',
  'mergermarket.com',
  'morningstar.com',
  'nbcnews.com',
  'news.ycombinator.com',
  'nikkei.com',
  'nytimes.com',
  'pitchbook.com',
  'politico.com',
  'qz.com',
  'reddit.com',
  'reuters.com',
  'semafor.com',
  'slashdot.org',
  'spglobal.com',
  'techcrunch.com',
  'techmeme.com',
  'threads.net',
  'thedeal.com',
  'theinformation.com',
  'theatlantic.com',
  'thehill.com',
  'theregister.com',
  'theverge.com',
  'tiktok.com',
  'time.com',
  'tomshardware.com',
  'usatoday.com',
  'tumblr.com',
  'vimeo.com',
  'washingtonpost.com',
  'wired.com',
  'x.com',
  'wsj.com',
  'youtube.com',
  'zdnet.com',
  'quartz.com',
]
